// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: omnychat/v1/omnychat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wraps every WebSocket binary frame.
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Error
	//	*Envelope_Auth
	//	*Envelope_AuthOk
	//	*Envelope_JoinRoom
	//	*Envelope_JoinOk
	//	*Envelope_LeaveRoom
	//	*Envelope_LeaveOk
	//	*Envelope_SendMessage
	//	*Envelope_MessageAck
	//	*Envelope_MessageEvent
	//	*Envelope_Typing
	//	*Envelope_TypingEvent
	//	*Envelope_ReadReceipt
	//	*Envelope_ReceiptEvent
	//	*Envelope_SyncRoom
	//	*Envelope_SyncComplete
	//	*Envelope_EditMessage
	//	*Envelope_DeleteMessage
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetAuth() *Auth {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *Envelope) GetAuthOk() *AuthOK {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthOk); ok {
			return x.AuthOk
		}
	}
	return nil
}

func (x *Envelope) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Envelope) GetJoinOk() *JoinOK {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_JoinOk); ok {
			return x.JoinOk
		}
	}
	return nil
}

func (x *Envelope) GetLeaveRoom() *LeaveRoom {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *Envelope) GetLeaveOk() *LeaveOK {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LeaveOk); ok {
			return x.LeaveOk
		}
	}
	return nil
}

func (x *Envelope) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *Envelope) GetMessageAck() *MessageAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageAck); ok {
			return x.MessageAck
		}
	}
	return nil
}

func (x *Envelope) GetMessageEvent() *MessageEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *Envelope) GetTyping() *Typing {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *Envelope) GetTypingEvent() *TypingEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TypingEvent); ok {
			return x.TypingEvent
		}
	}
	return nil
}

func (x *Envelope) GetReadReceipt() *ReadReceipt {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

func (x *Envelope) GetReceiptEvent() *ReceiptEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReceiptEvent); ok {
			return x.ReceiptEvent
		}
	}
	return nil
}

func (x *Envelope) GetSyncRoom() *SyncRoom {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncRoom); ok {
			return x.SyncRoom
		}
	}
	return nil
}

func (x *Envelope) GetSyncComplete() *SyncComplete {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncComplete); ok {
			return x.SyncComplete
		}
	}
	return nil
}

func (x *Envelope) GetEditMessage() *EditMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_EditMessage); ok {
			return x.EditMessage
		}
	}
	return nil
}

func (x *Envelope) GetDeleteMessage() *DeleteMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DeleteMessage); ok {
			return x.DeleteMessage
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

type Envelope_Auth struct {
	Auth *Auth `protobuf:"bytes,11,opt,name=auth,proto3,oneof"`
}

type Envelope_AuthOk struct {
	AuthOk *AuthOK `protobuf:"bytes,12,opt,name=auth_ok,json=authOk,proto3,oneof"`
}

type Envelope_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,13,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Envelope_JoinOk struct {
	JoinOk *JoinOK `protobuf:"bytes,14,opt,name=join_ok,json=joinOk,proto3,oneof"`
}

type Envelope_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,15,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Envelope_LeaveOk struct {
	LeaveOk *LeaveOK `protobuf:"bytes,16,opt,name=leave_ok,json=leaveOk,proto3,oneof"`
}

type Envelope_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,17,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type Envelope_MessageAck struct {
	MessageAck *MessageAck `protobuf:"bytes,18,opt,name=message_ack,json=messageAck,proto3,oneof"`
}

type Envelope_MessageEvent struct {
	MessageEvent *MessageEvent `protobuf:"bytes,19,opt,name=message_event,json=messageEvent,proto3,oneof"`
}

type Envelope_Typing struct {
	Typing *Typing `protobuf:"bytes,20,opt,name=typing,proto3,oneof"`
}

type Envelope_TypingEvent struct {
	TypingEvent *TypingEvent `protobuf:"bytes,21,opt,name=typing_event,json=typingEvent,proto3,oneof"`
}

type Envelope_ReadReceipt struct {
	ReadReceipt *ReadReceipt `protobuf:"bytes,22,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

type Envelope_ReceiptEvent struct {
	ReceiptEvent *ReceiptEvent `protobuf:"bytes,23,opt,name=receipt_event,json=receiptEvent,proto3,oneof"`
}

type Envelope_SyncRoom struct {
	SyncRoom *SyncRoom `protobuf:"bytes,24,opt,name=sync_room,json=syncRoom,proto3,oneof"`
}

type Envelope_SyncComplete struct {
	SyncComplete *SyncComplete `protobuf:"bytes,25,opt,name=sync_complete,json=syncComplete,proto3,oneof"`
}

type Envelope_EditMessage struct {
	EditMessage *EditMessage `protobuf:"bytes,30,opt,name=edit_message,json=editMessage,proto3,oneof"`
}

type Envelope_DeleteMessage struct {
	DeleteMessage *DeleteMessage `protobuf:"bytes,31,opt,name=delete_message,json=deleteMessage,proto3,oneof"`
}

func (*Envelope_Error) isEnvelope_Payload() {}

func (*Envelope_Auth) isEnvelope_Payload() {}

func (*Envelope_AuthOk) isEnvelope_Payload() {}

func (*Envelope_JoinRoom) isEnvelope_Payload() {}

func (*Envelope_JoinOk) isEnvelope_Payload() {}

func (*Envelope_LeaveRoom) isEnvelope_Payload() {}

func (*Envelope_LeaveOk) isEnvelope_Payload() {}

func (*Envelope_SendMessage) isEnvelope_Payload() {}

func (*Envelope_MessageAck) isEnvelope_Payload() {}

func (*Envelope_MessageEvent) isEnvelope_Payload() {}

func (*Envelope_Typing) isEnvelope_Payload() {}

func (*Envelope_TypingEvent) isEnvelope_Payload() {}

func (*Envelope_ReadReceipt) isEnvelope_Payload() {}

func (*Envelope_ReceiptEvent) isEnvelope_Payload() {}

func (*Envelope_SyncRoom) isEnvelope_Payload() {}

func (*Envelope_SyncComplete) isEnvelope_Payload() {}

func (*Envelope_EditMessage) isEnvelope_Payload() {}

func (*Envelope_DeleteMessage) isEnvelope_Payload() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthOK struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerTimeUnixMs int64                  `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthOK) Reset() {
	*x = AuthOK{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOK) ProtoMessage() {}

func (x *AuthOK) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOK.ProtoReflect.Descriptor instead.
func (*AuthOK) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{3}
}

func (x *AuthOK) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthOK) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinOK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LatestSeq     uint64                 `protobuf:"varint,2,opt,name=latest_seq,json=latestSeq,proto3" json:"latest_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinOK) Reset() {
	*x = JoinOK{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinOK) ProtoMessage() {}

func (x *JoinOK) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinOK.ProtoReflect.Descriptor instead.
func (*JoinOK) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{5}
}

func (x *JoinOK) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinOK) GetLatestSeq() uint64 {
	if x != nil {
		return x.LatestSeq
	}
	return 0
}

type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveOK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveOK) Reset() {
	*x = LeaveOK{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveOK) ProtoMessage() {}

func (x *LeaveOK) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveOK.ProtoReflect.Descriptor instead.
func (*LeaveOK) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveOK) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MessageAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientMsgId     string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ServerMsgId     string                 `protobuf:"bytes,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	Seq             uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{9}
}

func (x *MessageAck) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageAck) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MessageAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageAck) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type MessageEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientMsgId     string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ServerMsgId     string                 `protobuf:"bytes,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Body            string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Seq             uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,7,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	// Sync cursor: equals seq on create; advances on edit/delete without changing seq.
	UpdateSeq      uint64 `protobuf:"varint,8,opt,name=update_seq,json=updateSeq,proto3" json:"update_seq,omitempty"`
	EditedAtUnixMs int64  `protobuf:"varint,9,opt,name=edited_at_unix_ms,json=editedAtUnixMs,proto3" json:"edited_at_unix_ms,omitempty"`
	Deleted        bool   `protobuf:"varint,10,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{10}
}

func (x *MessageEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageEvent) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageEvent) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MessageEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessageEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageEvent) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *MessageEvent) GetUpdateSeq() uint64 {
	if x != nil {
		return x.UpdateSeq
	}
	return 0
}

func (x *MessageEvent) GetEditedAtUnixMs() int64 {
	if x != nil {
		return x.EditedAtUnixMs
	}
	return 0
}

func (x *MessageEvent) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type Typing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	IsTyping      bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Typing) Reset() {
	*x = Typing{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Typing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typing) ProtoMessage() {}

func (x *Typing) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Typing.ProtoReflect.Descriptor instead.
func (*Typing) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{11}
}

func (x *Typing) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Typing) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type TypingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsTyping      bool                   `protobuf:"varint,3,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{12}
}

func (x *TypingEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TypingEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingEvent) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type ReadReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LastReadSeq   uint64                 `protobuf:"varint,2,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceipt) Reset() {
	*x = ReadReceipt{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceipt) ProtoMessage() {}

func (x *ReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceipt.ProtoReflect.Descriptor instead.
func (*ReadReceipt) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{13}
}

func (x *ReadReceipt) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReadReceipt) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

type ReceiptEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastReadSeq     uint64                 `protobuf:"varint,3,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,4,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceiptEvent) Reset() {
	*x = ReceiptEvent{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptEvent) ProtoMessage() {}

func (x *ReceiptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptEvent.ProtoReflect.Descriptor instead.
func (*ReceiptEvent) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{14}
}

func (x *ReceiptEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReceiptEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReceiptEvent) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *ReceiptEvent) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type SyncRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRoom) Reset() {
	*x = SyncRoom{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRoom) ProtoMessage() {}

func (x *SyncRoom) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRoom.ProtoReflect.Descriptor instead.
func (*SyncRoom) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{15}
}

func (x *SyncRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncRoom) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *SyncRoom) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LatestSeq     uint64                 `protobuf:"varint,2,opt,name=latest_seq,json=latestSeq,proto3" json:"latest_seq,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncComplete) Reset() {
	*x = SyncComplete{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncComplete) ProtoMessage() {}

func (x *SyncComplete) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncComplete.ProtoReflect.Descriptor instead.
func (*SyncComplete) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{16}
}

func (x *SyncComplete) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SyncComplete) GetLatestSeq() uint64 {
	if x != nil {
		return x.LatestSeq
	}
	return 0
}

func (x *SyncComplete) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ServerMsgId   string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessage) Reset() {
	*x = EditMessage{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessage) ProtoMessage() {}

func (x *EditMessage) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessage.ProtoReflect.Descriptor instead.
func (*EditMessage) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{17}
}

func (x *EditMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EditMessage) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *EditMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type DeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ServerMsgId   string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessage) Reset() {
	*x = DeleteMessage{}
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessage) ProtoMessage() {}

func (x *DeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_omnychat_v1_omnychat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessage.ProtoReflect.Descriptor instead.
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return file_omnychat_v1_omnychat_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DeleteMessage) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

var File_omnychat_v1_omnychat_proto protoreflect.FileDescriptor

var file_omnychat_v1_omnychat_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x6d,
	0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f, 0x6d,
	0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x22, 0xb3, 0x08, 0x0a, 0x08, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x48, 0x00, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x6f, 0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x6d,
	0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x4f, 0x4b,
	0x48, 0x00, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x4f, 0x6b, 0x12, 0x34, 0x0a, 0x09, 0x6a, 0x6f,
	0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x2e, 0x0a, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x6f, 0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x4b, 0x48, 0x00, 0x52, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x4f, 0x6b,
	0x12, 0x37, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x00, 0x52, 0x09,
	0x6c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x65, 0x61,
	0x76, 0x65, 0x5f, 0x6f, 0x6b, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x6d,
	0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4f,
	0x4b, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x4f, 0x6b, 0x12, 0x3d, 0x0a, 0x0c,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b,
	0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x40, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x79, 0x70,
	0x69, 0x6e, 0x67, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x6d, 0x6e, 0x69,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x48, 0x00,
	0x52, 0x06, 0x74, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x3d, 0x0a, 0x0c, 0x74, 0x79, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70,
	0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x79, 0x70, 0x69,
	0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x6d,
	0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x6f,
	0x6f, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x40,
	0x0a, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18,
	0x19, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0c, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x3d, 0x0a, 0x0c, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x0b, 0x65, 0x64, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x43, 0x0a, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1c, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x50, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x4f, 0x4b, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x22, 0x23, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x06, 0x4a,
	0x6f, 0x69, 0x6e, 0x4f, 0x4b, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x65, 0x71, 0x22, 0x24, 0x0a,
	0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x07, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x4f, 0x4b, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xac, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x12, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x22, 0xc3, 0x02, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x12, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x11, 0x65, 0x64, 0x69, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x65, 0x64, 0x69, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78,
	0x4d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x3e, 0x0a, 0x06,
	0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x5c, 0x0a, 0x0b,
	0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x54, 0x79, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x4a, 0x0a, 0x0b, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x65, 0x71, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x71, 0x12, 0x2b, 0x0a,
	0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78,
	0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x22, 0x56, 0x0a, 0x08, 0x53, 0x79,
	0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x61, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x53, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61,
	0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61,
	0x73, 0x4d, 0x6f, 0x72, 0x65, 0x22, 0x5e, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x4c, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x6d, 0x6e, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x6f, 0x6d, 0x6e, 0x69, 0x63,
	0x68, 0x61, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_omnychat_v1_omnychat_proto_rawDescOnce sync.Once
	file_omnychat_v1_omnychat_proto_rawDescData []byte
)

func file_omnychat_v1_omnychat_proto_rawDescGZIP() []byte {
	file_omnychat_v1_omnychat_proto_rawDescOnce.Do(func() {
		file_omnychat_v1_omnychat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omnychat_v1_omnychat_proto_rawDesc), len(file_omnychat_v1_omnychat_proto_rawDesc)))
	})
	return file_omnychat_v1_omnychat_proto_rawDescData
}

var file_omnychat_v1_omnychat_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_omnychat_v1_omnychat_proto_goTypes = []any{
	(*Envelope)(nil),      // 0: omnychat.v1.Envelope
	(*Error)(nil),         // 1: omnychat.v1.Error
	(*Auth)(nil),          // 2: omnychat.v1.Auth
	(*AuthOK)(nil),        // 3: omnychat.v1.AuthOK
	(*JoinRoom)(nil),      // 4: omnychat.v1.JoinRoom
	(*JoinOK)(nil),        // 5: omnychat.v1.JoinOK
	(*LeaveRoom)(nil),     // 6: omnychat.v1.LeaveRoom
	(*LeaveOK)(nil),       // 7: omnychat.v1.LeaveOK
	(*SendMessage)(nil),   // 8: omnychat.v1.SendMessage
	(*MessageAck)(nil),    // 9: omnychat.v1.MessageAck
	(*MessageEvent)(nil),  // 10: omnychat.v1.MessageEvent
	(*Typing)(nil),        // 11: omnychat.v1.Typing
	(*TypingEvent)(nil),   // 12: omnychat.v1.TypingEvent
	(*ReadReceipt)(nil),   // 13: omnychat.v1.ReadReceipt
	(*ReceiptEvent)(nil),  // 14: omnychat.v1.ReceiptEvent
	(*SyncRoom)(nil),      // 15: omnychat.v1.SyncRoom
	(*SyncComplete)(nil),  // 16: omnychat.v1.SyncComplete
	(*EditMessage)(nil),   // 17: omnychat.v1.EditMessage
	(*DeleteMessage)(nil), // 18: omnychat.v1.DeleteMessage
}
var file_omnychat_v1_omnychat_proto_depIdxs = []int32{
	1,  // 0: omnychat.v1.Envelope.error:type_name -> omnychat.v1.Error
	2,  // 1: omnychat.v1.Envelope.auth:type_name -> omnychat.v1.Auth
	3,  // 2: omnychat.v1.Envelope.auth_ok:type_name -> omnychat.v1.AuthOK
	4,  // 3: omnychat.v1.Envelope.join_room:type_name -> omnychat.v1.JoinRoom
	5,  // 4: omnychat.v1.Envelope.join_ok:type_name -> omnychat.v1.JoinOK
	6,  // 5: omnychat.v1.Envelope.leave_room:type_name -> omnychat.v1.LeaveRoom
	7,  // 6: omnychat.v1.Envelope.leave_ok:type_name -> omnychat.v1.LeaveOK
	8,  // 7: omnychat.v1.Envelope.send_message:type_name -> omnychat.v1.SendMessage
	9,  // 8: omnychat.v1.Envelope.message_ack:type_name -> omnychat.v1.MessageAck
	10, // 9: omnychat.v1.Envelope.message_event:type_name -> omnychat.v1.MessageEvent
	11, // 10: omnychat.v1.Envelope.typing:type_name -> omnychat.v1.Typing
	12, // 11: omnychat.v1.Envelope.typing_event:type_name -> omnychat.v1.TypingEvent
	13, // 12: omnychat.v1.Envelope.read_receipt:type_name -> omnychat.v1.ReadReceipt
	14, // 13: omnychat.v1.Envelope.receipt_event:type_name -> omnychat.v1.ReceiptEvent
	15, // 14: omnychat.v1.Envelope.sync_room:type_name -> omnychat.v1.SyncRoom
	16, // 15: omnychat.v1.Envelope.sync_complete:type_name -> omnychat.v1.SyncComplete
	17, // 16: omnychat.v1.Envelope.edit_message:type_name -> omnychat.v1.EditMessage
	18, // 17: omnychat.v1.Envelope.delete_message:type_name -> omnychat.v1.DeleteMessage
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_omnychat_v1_omnychat_proto_init() }
func file_omnychat_v1_omnychat_proto_init() {
	if File_omnychat_v1_omnychat_proto != nil {
		return
	}
	file_omnychat_v1_omnychat_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Error)(nil),
		(*Envelope_Auth)(nil),
		(*Envelope_AuthOk)(nil),
		(*Envelope_JoinRoom)(nil),
		(*Envelope_JoinOk)(nil),
		(*Envelope_LeaveRoom)(nil),
		(*Envelope_LeaveOk)(nil),
		(*Envelope_SendMessage)(nil),
		(*Envelope_MessageAck)(nil),
		(*Envelope_MessageEvent)(nil),
		(*Envelope_Typing)(nil),
		(*Envelope_TypingEvent)(nil),
		(*Envelope_ReadReceipt)(nil),
		(*Envelope_ReceiptEvent)(nil),
		(*Envelope_SyncRoom)(nil),
		(*Envelope_SyncComplete)(nil),
		(*Envelope_EditMessage)(nil),
		(*Envelope_DeleteMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omnychat_v1_omnychat_proto_rawDesc), len(file_omnychat_v1_omnychat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omnychat_v1_omnychat_proto_goTypes,
		DependencyIndexes: file_omnychat_v1_omnychat_proto_depIdxs,
		MessageInfos:      file_omnychat_v1_omnychat_proto_msgTypes,
	}.Build()
	File_omnychat_v1_omnychat_proto = out.File
	file_omnychat_v1_omnychat_proto_goTypes = nil
	file_omnychat_v1_omnychat_proto_depIdxs = nil
}
